### ISSUE TITLE
Search by name doesn't work with cyrillic 

### ISSUE THREAD

**Issue by Crabar** [drinkit/drinkit-server#1]
Search with cyrillic symbols find nothing. It could be problem with encoding.

**Comment by pkolmykov** [comment]
Resolved by adding _URIEncoding="UTF-8"_ into tomcat configuration on server.
See http://stackoverflow.com/questions/8909130/how-to-configure-uriencoding-for-a-certain-web-application
_Note: variant with CharacterEncodingFilter + useBodyEncodingForURI="true" working fine locally but not working in openshift_
